-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgy5OwIpBCL3EuJMkm
evo7BuTOlFA8zu0d8E3Wf/QgmvWgCgYIKoZIzj0DAQehRANCAAT+/1XT+YktnytJ
9+Ag7qHqIWWaI+l9xs2USQMUKpCUh8/QJiYessTTKNg3KJlIXOTfTN0u+hSSFLxh
yk12a8L0
-----END PRIVATE KEY-----